#Project Config
smart:
  name: smart
  version: 0.0.1
  copyrightYear: 2018

  profile: D:/profile/
  addressEnabled: true

#Dev Config
server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100
    min-spare-threads: 10

#日志配置
logging:
  level:
    com.facedamon: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug

#用户配置
user:
  password:
    #密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

#Spring Config
spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    # 禁用缓存
    cache: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    #load application-druid.yml
    active: druid
  #文件上传
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  #热部署开关
  devtools:
    restart:
      enabled: true


#MyBatis
mybatis:

  #搜索指定包别名
  type-aliases-package: com.facedamon
  #配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  #加载全局的配置文件
  #config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    cache-enabled: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

#PageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#Shiro
shiro:
  user:
    #登录地址
    loginUrl: /login
    #认证失败地址
    unauthorizedUrl: /unauth
    #首页地址
    indexUrl : /index
    #验证码开关
    captchaEnabled : false
    #验证码类型 match char
    captchaType : math
  cookie:
    #设置Cookie的域名 默认空，即当前访问的域名
    domain:
    #设置cookie的有效访问路径
    path: /
    #设置HttpOnly属性
    #如何保障我们的Cookie安全呢？
    #Cookie都是通过document对象获取的，我们如果能让cookie在浏览器中不可见就可以了，
    #那HttpOnly就是在设置cookie时接受这样一个参数，一旦被设置，在浏览器的document对象中就看不到cookie了。
    #而浏览器在浏览网页的时候不受任何影响，因为Cookie会被放在浏览器头中发送出去(包括Ajax的时候)，
    #应用程序也一般不会在JS里操作这些敏感Cookie的，对于一些敏感的Cookie我们采用HttpOnly，
    #对于一些需要在应用程序中用JS操作的cookie我们就不予设置，这样就保障了Cookie信息的安全也保证了应用
    httpOnly: true
    #设置Cookie的过期时间.单位天
    maxAge: 30
  session:
    #Session超时时间（默认30分钟）
    expireTime: 30
    #同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    #相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

#异步线程池
async:
  #最大线程
  maxPoolSize: 10
  #队列阈值
  queueCapacity: 100
  #最大保留时长 单位秒
  keepAliveSeconds: 120

#generator
generator:
  author: facedamon
  packageName: com.facedamon.smart.project.module
  autoRemovePre: true
  tablePrefix: sys_